//
// CreateMerchant400Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct CreateMerchant400Response: Codable, JSONEncodable, Hashable {

    static let dataRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var data: String?
    public var error: CreateMerchant400ResponseError?

    public init(data: String? = nil, error: CreateMerchant400ResponseError? = nil) {
        self.data = data
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case error
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(error, forKey: .error)
    }
}
