//
// CreateAddressRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct CreateAddressRequest: Codable, JSONEncodable, Hashable {

    public var additionalDescription: String?
    public var address1: String?
    public var address2: String?
    public var addressType: String?
    public var city: String?
    public var country: String?
    public var firstName: String?
    public var identityDocument: String?
    public var isBillingAddress: Bool?
    public var isDefault: Bool?
    public var lastName: String?
    public var lat: Int?
    public var lng: Int?
    public var phone: String?
    public var stateName: String?
    public var zipcode: String?

    public init(additionalDescription: String? = nil, address1: String? = nil, address2: String? = nil, addressType: String? = nil, city: String? = nil, country: String? = nil, firstName: String? = nil, identityDocument: String? = nil, isBillingAddress: Bool? = nil, isDefault: Bool? = nil, lastName: String? = nil, lat: Int? = nil, lng: Int? = nil, phone: String? = nil, stateName: String? = nil, zipcode: String? = nil) {
        self.additionalDescription = additionalDescription
        self.address1 = address1
        self.address2 = address2
        self.addressType = addressType
        self.city = city
        self.country = country
        self.firstName = firstName
        self.identityDocument = identityDocument
        self.isBillingAddress = isBillingAddress
        self.isDefault = isDefault
        self.lastName = lastName
        self.lat = lat
        self.lng = lng
        self.phone = phone
        self.stateName = stateName
        self.zipcode = zipcode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case additionalDescription = "additional_description"
        case address1
        case address2
        case addressType = "address_type"
        case city
        case country
        case firstName = "first_name"
        case identityDocument = "identity_document"
        case isBillingAddress = "is_billing_address"
        case isDefault = "is_default"
        case lastName = "last_name"
        case lat
        case lng
        case phone
        case stateName = "state_name"
        case zipcode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(additionalDescription, forKey: .additionalDescription)
        try container.encodeIfPresent(address1, forKey: .address1)
        try container.encodeIfPresent(address2, forKey: .address2)
        try container.encodeIfPresent(addressType, forKey: .addressType)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(identityDocument, forKey: .identityDocument)
        try container.encodeIfPresent(isBillingAddress, forKey: .isBillingAddress)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lng, forKey: .lng)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(stateName, forKey: .stateName)
        try container.encodeIfPresent(zipcode, forKey: .zipcode)
    }
}

