//
// GetInstallments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetInstallments200Response: Codable, JSONEncodable, Hashable {

    public var installments: [GetInstallments200ResponseInstallmentsInner]?

    public init(installments: [GetInstallments200ResponseInstallmentsInner]? = nil) {
        self.installments = installments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case installments
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(installments, forKey: .installments)
    }
}
