//
// GetMerchantsPaymentsMethods200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMerchantsPaymentsMethods200Response: Codable, JSONEncodable, Hashable {

    /** Lista de los métodos de pago de la tienda para esa orden */
    public var data: [GetMerchantsPaymentsMethods200ResponseDataInner]?

    public init(data: [GetMerchantsPaymentsMethods200ResponseDataInner]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

