//
// GetMerchantsPaymentsMethods200ResponseDataInnerInputSchemaInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMerchantsPaymentsMethods200ResponseDataInnerInputSchemaInner: Codable, JSONEncodable, Hashable {

    /** Si siempre es requerido o no. */
    public var always: Bool?
    /** Nombre del campo para realizar un pago  */
    public var name: String?
    /** Si el campo es requerido para realizar el pago */
    public var _required: Bool?
    /** Tipo de dato */
    public var type: String?

    public init(always: Bool? = nil, name: String? = nil, _required: Bool? = nil, type: String? = nil) {
        self.always = always
        self.name = name
        self._required = _required
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case always
        case name
        case _required = "required"
        case type
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(always, forKey: .always)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(type, forKey: .type)
    }
}
