//
// GetMerchantsPaymentsMethods200ResponseDataInnerLabels.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMerchantsPaymentsMethods200ResponseDataInnerLabels: Codable, JSONEncodable, Hashable {

    public var es: String?

    public init(es: String? = nil) {
        self.es = es
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case es
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(es, forKey: .es)
    }
}

