//
// GetMerchantsPaymentsMethods500Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMerchantsPaymentsMethods500Response: Codable, JSONEncodable, Hashable {

    public var data: AnyCodable?
    public var error: OrderToken400ResponseError?

    public init(data: AnyCodable? = nil, error: OrderToken400ResponseError? = nil) {
        self.data = data
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case error
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(error, forKey: .error)
    }
}
