//
// GetOrder200ResponseOrderShippingOptionsDetailsContact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Contacto de la tienda */
public struct GetOrder200ResponseOrderShippingOptionsDetailsContact: Codable, JSONEncodable, Hashable {

    /** Nombre del contacto del comercio */
    public var name: String?
    public var phone: GetOrder200ResponseOrderShippingOptionsDetailsContactPhone?

    public init(name: String? = nil, phone: GetOrder200ResponseOrderShippingOptionsDetailsContactPhone? = nil) {
        self.name = name
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case phone
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}
