//
// GetOrder200ResponseOrderShippingOptionsDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** El detalle del método de envío  */
public struct GetOrder200ResponseOrderShippingOptionsDetails: Codable, JSONEncodable, Hashable {

    public var additionalDetails: OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails?
    /** Dirección de la tienda */
    public var address: String?
    public var addressCoordinates: OrderToken200ResponseOrderShippingOptionsDetailsAddressCoordinates?
    public var contact: GetOrder200ResponseOrderShippingOptionsDetailsContact?
    /** Nombre de la tienda, por defecto te devolvera all */
    public var storeName: String?

    public init(additionalDetails: OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails? = nil, address: String? = nil, addressCoordinates: OrderToken200ResponseOrderShippingOptionsDetailsAddressCoordinates? = nil, contact: GetOrder200ResponseOrderShippingOptionsDetailsContact? = nil, storeName: String? = nil) {
        self.additionalDetails = additionalDetails
        self.address = address
        self.addressCoordinates = addressCoordinates
        self.contact = contact
        self.storeName = storeName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case additionalDetails = "additional_details"
        case address
        case addressCoordinates = "address_coordinates"
        case contact
        case storeName = "store_name"
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(additionalDetails, forKey: .additionalDetails)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(addressCoordinates, forKey: .addressCoordinates)
        try container.encodeIfPresent(contact, forKey: .contact)
        try container.encodeIfPresent(storeName, forKey: .storeName)
    }
}
