//
// GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner: Codable, JSONEncodable, Hashable {

    /** Descripción de la institución financiera. */
    public var description: String?
    /** Identificador de la institución financiera. */
    public var id: String?

    public init(description: String? = nil, id: String? = nil) {
        self.description = description
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description = "Description"
        case id = "Id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

