//
// GetPaymentMethods200ResponseDataInnerSpecificFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Campos específicos para el método de pago. */
public struct GetPaymentMethods200ResponseDataInnerSpecificFields: Codable, JSONEncodable, Hashable {

    public var financialInstitutions: [GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner]?

    public init(financialInstitutions: [GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner]? = nil) {
        self.financialInstitutions = financialInstitutions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case financialInstitutions = "financial_institutions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(financialInstitutions, forKey: .financialInstitutions)
    }
}

