//
// GetUserAddresses200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUserAddresses200Response: Codable, JSONEncodable, Hashable {

    /** Objeto con las direcciones del cliente */
    public var data: [GetUserAddresses200ResponseDataInner]?

    public init(data: [GetUserAddresses200ResponseDataInner]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

