//
// IdentityToken200ResponseMerchantEventsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IdentityToken200ResponseMerchantEventsInner: Codable, JSONEncodable, Hashable {

    public var ID: Int?
    public var createdAt: String?
    public var deletedAt: String?
    public var event: String?
    public var merchantId: String?
    public var updatedAt: String?

    public init(ID: Int? = nil, createdAt: String? = nil, deletedAt: String? = nil, event: String? = nil, merchantId: String? = nil, updatedAt: String? = nil) {
        self.ID = ID
        self.createdAt = createdAt
        self.deletedAt = deletedAt
        self.event = event
        self.merchantId = merchantId
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case createdAt = "created_at"
        case deletedAt = "deleted_at"
        case event
        case merchantId = "merchant_id"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ID, forKey: .ID)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(merchantId, forKey: .merchantId)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

