//
// MerchantsMerchantIdApplicationsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct MerchantsMerchantIdApplicationsPostRequest: Codable, JSONEncodable, Hashable {

    static let expireAtRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var expireAt: String?
    public var isSandbox: Bool?
    public var name: String?

    public init(expireAt: String? = nil, isSandbox: Bool? = nil, name: String? = nil) {
        self.expireAt = expireAt
        self.isSandbox = isSandbox
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expireAt = "expire_at"
        case isSandbox = "is_sandbox"
        case name
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(expireAt, forKey: .expireAt)
        try container.encodeIfPresent(isSandbox, forKey: .isSandbox)
        try container.encodeIfPresent(name, forKey: .name)
    }
}
