//
// OrderToken200ResponseOrderDiscountsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderToken200ResponseOrderDiscountsInner: Codable, JSONEncodable, Hashable {

    /** El monto total del descuento de la orden. */
    public var amount: Double?
    /** El código del descuento que se aplicara en la orden */
    public var code: String?
    /** La descripción del descuento */
    public var description: String?
    /** URL del descuento */
    public var detailsUrl: String?
    /** Categoría del descuento */
    public var discountCategory: String?
    public var freeShipping: OrderToken200ResponseOrderDiscountsInnerFreeShipping?
    /** Referencia del descuento */
    public var reference: String?

    public init(amount: Double? = nil, code: String? = nil, description: String? = nil, detailsUrl: String? = nil, discountCategory: String? = nil, freeShipping: OrderToken200ResponseOrderDiscountsInnerFreeShipping? = nil, reference: String? = nil) {
        self.amount = amount
        self.code = code
        self.description = description
        self.detailsUrl = detailsUrl
        self.discountCategory = discountCategory
        self.freeShipping = freeShipping
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case code
        case description
        case detailsUrl = "details_url"
        case discountCategory = "discount_category"
        case freeShipping = "free_shipping"
        case reference
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(detailsUrl, forKey: .detailsUrl)
        try container.encodeIfPresent(discountCategory, forKey: .discountCategory)
        try container.encodeIfPresent(freeShipping, forKey: .freeShipping)
        try container.encodeIfPresent(reference, forKey: .reference)
    }
}
