//
// OrderToken200ResponseOrderDiscountsInnerFreeShipping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderToken200ResponseOrderDiscountsInnerFreeShipping: Codable, JSONEncodable, Hashable {

    /** Si el producto tiene envío gratis */
    public var isFreeShipping: Bool? = false
    /** El monto maximo del descuento. */
    public var maximumCostAllowed: Double?

    public init(isFreeShipping: Bool? = false, maximumCostAllowed: Double? = nil) {
        self.isFreeShipping = isFreeShipping
        self.maximumCostAllowed = maximumCostAllowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isFreeShipping = "is_free_shipping"
        case maximumCostAllowed = "maximum_cost_allowed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isFreeShipping, forKey: .isFreeShipping)
        try container.encodeIfPresent(maximumCostAllowed, forKey: .maximumCostAllowed)
    }
}

