//
// OrderTokenRequestOrderItemsInnerDiscountsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderTokenRequestOrderItemsInnerDiscountsInner: Codable, JSONEncodable, Hashable {

    /** El monto total del descuento de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    public var amount: Double
    /** ID de referencia del descuento que se aplicara en la orden */
    public var refIdx: Double

    public init(amount: Double, refIdx: Double) {
        self.amount = amount
        self.refIdx = refIdx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case refIdx = "ref_idx"
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(refIdx, forKey: .refIdx)
    }
}
