//
// OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Detalles adicionales, puede llevar campos diferentes campos como  pickup_time | stock_location */
public struct OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails: Codable, JSONEncodable, Hashable {

    static let pickupTimeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Hora de recojo */
    public var pickupTime: String?
    /** Nombre de la tienda para recojo */
    public var stockLocation: String?

    public init(pickupTime: String? = nil, stockLocation: String? = nil) {
        self.pickupTime = pickupTime
        self.stockLocation = stockLocation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pickupTime = "pickup_time"
        case stockLocation = "stock_location"
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pickupTime, forKey: .pickupTime)
        try container.encodeIfPresent(stockLocation, forKey: .stockLocation)
    }
}
