//
// OrderTokenRequestOrderShippingMethodSchedulerInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderTokenRequestOrderShippingMethodSchedulerInner: Codable, JSONEncodable, Hashable {

    /** Fecha de envío programada */
    public var date: String?
    /** Hora final/límite configurada pra realizar el envío */
    public var endTime: String?
    /** Hora inicial configurada pra realizar el envío */
    public var startTime: String?
    /** Intérvalo de tiempo entre las horas programadas del envío */
    public var stepsMinutes: Double?

    public init(date: String? = nil, endTime: String? = nil, startTime: String? = nil, stepsMinutes: Double? = nil) {
        self.date = date
        self.endTime = endTime
        self.startTime = startTime
        self.stepsMinutes = stepsMinutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case endTime = "end_time"
        case startTime = "start_time"
        case stepsMinutes = "steps_minutes"
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(endTime, forKey: .endTime)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(stepsMinutes, forKey: .stepsMinutes)
    }
}
