//
// OrderToken200ResponseOrderShippingOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Son los métodos de envío disponibles de la orden, actualmente tenemos delivery y pickup */
public struct OrderToken200ResponseOrderShippingOptions: Codable, JSONEncodable, Hashable {

    public var details: OrderToken200ResponseOrderShippingOptionsDetails?
    /** Tipo de envío puede ser **delivery:**Entrega a domicilio del cliente, **pickup:**El cliente debera recoger la orden en la respectiva tienda, **dinein:**Cenar en la tienda, esto es una orden de pedido */
    public var type: String?

    public init(details: OrderToken200ResponseOrderShippingOptionsDetails? = nil, type: String? = nil) {
        self.details = details
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case details
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

