//
// OrderToken200ResponseOrderMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Agregar datos que se requieran adicionales de parte del comercio en clave-valor (JSON) */
public struct OrderToken200ResponseOrderMetadata: Codable, JSONEncodable, Hashable {

    public var origin: String?
    public var state: String?

    public init(origin: String? = nil, state: String? = nil) {
        self.origin = origin
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case origin
        case state
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encodeIfPresent(state, forKey: .state)
    }
}
