//
// OrderToken200ResponseOrderShipping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tarifa de envío */
public struct OrderToken200ResponseOrderShipping: Codable, JSONEncodable, Hashable {

    public var discounts: [AnyCodable]?
    /** Precio original de envío */
    public var originalAmount: Double?
    /** Descuento total en el envío */
    public var totalDiscount: Double?

    public init(discounts: [AnyCodable]? = nil, originalAmount: Double? = nil, totalDiscount: Double? = nil) {
        self.discounts = discounts
        self.originalAmount = originalAmount
        self.totalDiscount = totalDiscount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discounts
        case originalAmount = "original_amount"
        case totalDiscount = "total_discount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(discounts, forKey: .discounts)
        try container.encodeIfPresent(originalAmount, forKey: .originalAmount)
        try container.encodeIfPresent(totalDiscount, forKey: .totalDiscount)
    }
}

