//
// OrderTokenRequestOrderShippingOptionsDetailsAdditionalDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Detalles adicionales, puede llevar campos diferentes campos como  pickup_time | stock_location */
public struct OrderTokenRequestOrderShippingOptionsDetailsAdditionalDetails: Codable, JSONEncodable, Hashable {

    static let pickupTimeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Notas para la dirección, en caso sea **delivery** */
    public var addressNotes: String?
    /** Hora que el cliente tiene que recoger la orden, en caso sea **pickup** */
    public var pickupTime: String?
    /** Nombre de la tienda que el cliente tiene que recoger la orden, en caso sea **pickup** */
    public var stockLocation: String?

    public init(addressNotes: String? = nil, pickupTime: String? = nil, stockLocation: String? = nil) {
        self.addressNotes = addressNotes
        self.pickupTime = pickupTime
        self.stockLocation = stockLocation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressNotes = "address_notes"
        case pickupTime = "pickup_time"
        case stockLocation = "stock_location"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addressNotes, forKey: .addressNotes)
        try container.encodeIfPresent(pickupTime, forKey: .pickupTime)
        try container.encodeIfPresent(stockLocation, forKey: .stockLocation)
    }
}

