//
// OrderToken200ResponseOrderItemsInnerWeight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Peso del producto */
public struct OrderToken200ResponseOrderItemsInnerWeight: Codable, JSONEncodable, Hashable {

    /** Unidad de peso del producto */
    public var unit: String?
    /** Peso del producto */
    public var weight: Double?

    public init(unit: String? = nil, weight: Double? = nil) {
        self.unit = unit
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unit
        case weight
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(weight, forKey: .weight)
    }
}
