//
// OrderTokenRequestOrderShippingOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Son los métodos de envío disponibles de la orden, actualmente tenemos **delivery** y **pickup** */
public struct OrderTokenRequestOrderShippingOptions: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case delivery = "delivery"
        case pickup = "pickup"
        case empty = ""
    }
    static let typeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var details: OrderTokenRequestOrderShippingOptionsDetails
    /** Tipo de envío puede ser **delivery:**Entrega a domicilio del cliente, **pickup:**El cliente debera recoger la orden en la respectiva tienda, **dinein:**Cenar en la tienda, esto es una orden de pedido */
    public var type: ModelType

    public init(details: OrderTokenRequestOrderShippingOptionsDetails, type: ModelType) {
        self.details = details
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case details
        case type
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(details, forKey: .details)
        try container.encode(type, forKey: .type)
    }
}
