//
// RegisterUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterUserRequest: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var firstName: String?
    public var identityDocument: String?
    public var lastName: String?
    public var phone: String?

    public init(email: String? = nil, firstName: String? = nil, identityDocument: String? = nil, lastName: String? = nil, phone: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.identityDocument = identityDocument
        self.lastName = lastName
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName = "first_name"
        case identityDocument = "identity_document"
        case lastName = "last_name"
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(identityDocument, forKey: .identityDocument)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

