//
// UsersRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersRegisterRequest: Codable, JSONEncodable, Hashable {

    /** Correo del usuario a registrar */
    public var email: String
    /** Nombre del usuario */
    public var firstName: String
    /** Documento de identidad del usuario */
    public var identityDocument: String?
    /** Apellido del usuario */
    public var lastName: String
    /** Número de telefono del usuario */
    public var phone: String

    public init(email: String, firstName: String, identityDocument: String? = nil, lastName: String, phone: String) {
        self.email = email
        self.firstName = firstName
        self.identityDocument = identityDocument
        self.lastName = lastName
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case firstName = "first_name"
        case identityDocument = "identity_document"
        case lastName = "last_name"
        case phone
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(firstName, forKey: .firstName)
        try container.encodeIfPresent(identityDocument, forKey: .identityDocument)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(phone, forKey: .phone)
    }
}
