//
// UsersRegister201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersRegister201Response: Codable, JSONEncodable, Hashable {

    /** Token de la sesión del usuario */
    public var token: String?
    /** Identificador del usuario dentro de la red DEUNA */
    public var userId: String?

    public init(token: String? = nil, userId: String? = nil) {
        self.token = token
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

