//
// UsersLoginDeviceFingerprintPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct UsersLoginDeviceFingerprintPost200Response: Codable, JSONEncodable, Hashable {

    static let refreshTokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var refreshToken: String?
    public var token: String?
    public var userDeuna: Bool?

    public init(refreshToken: String? = nil, token: String? = nil, userDeuna: Bool? = nil) {
        self.refreshToken = refreshToken
        self.token = token
        self.userDeuna = userDeuna
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case refreshToken = "refresh_token"
        case token
        case userDeuna = "user-deuna"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(userDeuna, forKey: .userDeuna)
    }
}

