//
// VerifyPaymentOtp200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyPaymentOtp200Response: Codable, JSONEncodable, Hashable {

    public var order: VerifyPaymentOtp200ResponseOrder?
    /** Es el token de la orden generado por DEUNA, el mismo que será usado para el **Widget Checkout**  */
    public var token: String?

    public init(order: VerifyPaymentOtp200ResponseOrder? = nil, token: String? = nil) {
        self.order = order
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case token
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(token, forKey: .token)
    }
}
