//
// VerifyPaymentOtpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyPaymentOtpRequest: Codable, JSONEncodable, Hashable {

    /** Código OTP */
    public var otp: String?

    public init(otp: String? = nil) {
        self.otp = otp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case otp
    }

// Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(otp, forKey: .otp)
    }
}
